### ISSUE TITLE
Nvm Urls can't be resolved inside minikube

### ISSUE THREAD

**Issue by josepablofm78** [nevermined-io/tools#133]
## Describe the bug
if we start tools with the compute option enable, it will deploy a minikube instance to run the compute pods. Problem is that minikube (and the pods) are not able to resolve the URLs of the different components of Nevermined, like the keeper node, marketplace api, etc, unless you use host.docker.internal or host.minikube.internal

##  To Reproduce
1. run tools with the compute option: ./start_nevermined.sh --no-graph --no-gateway --compute
2. wait until minikube is up and running (you should see the line minikube  * NOTE: This process must stay alive for the mount to be accessible )
3.- minikube ssh
4.- curl http://localhost:3100 
the result will be curl: (7) Failed to connect to localhost port 3100: Connection refused
Same with 127.0.0.1, 0.0.0.0, etc
5.- curl host.docker.internal:3100
{"APIversion":"0.3.0","elasticsearchVersion":"7.13.2","docs":"http://host.docker.internal:3100/api/v1/docs"}

## Expected behavior
To be able to run the compute pods within tools, minikube should be able to resolve the URLs to nevermined components without using the docker or minikube internal host.

Using host.docker.internal to set the nevermined instance in the pods will work to create this instance correctly connected to NVM, but it won't be able, for instance, to resolve a Did published with local url for the metadata:
NeverminedFactory. NVM Instance created
/snapshot/node_modules/@nevermined-io/nevermined-sdk-js/dist/node/metadata/Metadata.js:147
                throw new errors_1.ApiError(error);
                      ^
ApiError: Api error: FetchError: request to http://127.0.0.1:3100/api/v1/metadata/assets/ddo/did:nv:64e6c555e7c462466c9d410eda4e0c3b43b3bdfa59de419a1f94781049c731c5 failed, reason: connect ECONNREFUSED

**Comment by r-marques** [comment]
replaced by https://github.com/nevermined-io/internal/issues/328
